### ISSUE TITLE
VST2 no longer builds

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/tuning-workbench-synth#125]
At the last stage when it's about to link the VST it fails

```
Compiling include_surgesynthteam_tuningui.cpp
Linking tuning-workbench-synth - Shared Code
Linking tuning-workbench-synth - VST
/usr/bin/ld: build/tuning-workbench-synth.a(TWSMainPanel_59eb4664.o): in function `TWSMainPanel::TWSMainPanel(TuningworkbenchsynthAudioProcessor&)':
/home/studio/dev/extras/tuning-workbench-synth/Builds/Linux/../../Source/TWSMainPanel.cpp:596: undefined reference to `Build::git_commit_hash[abi:cxx11]'
/usr/bin/ld: /home/studio/dev/extras/tuning-workbench-synth/Builds/Linux/../../Source/TWSMainPanel.cpp:596: undefined reference to `Build::build_date[abi:cxx11]'
/usr/bin/ld: build/tuning-workbench-synth.a(TWSAbout_fa234b26.o): in function `TWSAbout::TWSAbout()':
/home/studio/dev/extras/tuning-workbench-synth/Builds/Linux/../../Source/TWSAbout.cpp:106: undefined reference to `Build::git_commit_hash[abi:cxx11]'
/usr/bin/ld: /home/studio/dev/extras/tuning-workbench-synth/Builds/Linux/../../Source/TWSAbout.cpp:106: undefined reference to `Build::git_branch[abi:cxx11]'
collect2: error: ld returned 1 exit status
make: *** [Makefile:160: build/tuning-workbench-synth.so] Error 1

```

**Comment by baconpaul** [comment]
from slack this is a projucer- not a vst2- thing. cmake builds that info string set.

here’s a quick fix
12:15
build the vst3 with cmake
12:15
you will get a file called ‘buildin/generated/version.cpp’
12:16
move that to the source directory and call it ‘projucer-version-stub.cpp’
12:16
edit it so that the branch is ‘unknown’ and the has is ‘unknown’
12:16
add projucer-version-stub.cpp to the projucer
12:16
and it should ubild and link
12:16
if it does push it up as a pull request

**Comment by tank-trax** [comment]
that worked, also without the editing of branch and hash to unknown
it was optimum to disable VST3 from Projucer when using make from the JUCE `Builds/LinuxMakefile` folder 
thanks

**Comment by tank-trax** [comment]
as an FYI for the VST3 `strip -s tuning-workbench-synth.so` reduced the filesize from 12.9 to 7.6 MB

**Comment by baconpaul** [comment]
https://forum.juce.com/t/cmake-linux-vst3-not-stripped/39617/4 that's the strip change.
