### ISSUE TITLE
Drag and Drop of Presets

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/tuning-workbench-synth#84]

**Comment by baconpaul** [comment]
Hi @tank-trax 

Since I know you are in the code maybe you want to take a shot tat this. It’s really pretty easy!

The drag and drop handler is here

https://github.com/surge-synthesizer/tuning-workbench-synth/blob/6e5fe501f3a7059b9d1e0a5e538d263c8440ae82/Source/TWSMainPanel.cpp#L1404

And you can see how it does scl and kbm. You can add a twsxml after that

As to what you should do in the block, these 4 lines from the load menu are basically the same thing you need

https://github.com/surge-synthesizer/tuning-workbench-synth/blob/6e5fe501f3a7059b9d1e0a5e538d263c8440ae82/Source/TWSMainPanel.cpp#L1604

No pressure but thought you might like to try and get this working and tested! Up to you
